apps/posts/urls.py
from django.urls import path
from . import views, models


app_name = 'posts'
urlpatterns = [
 path('', views.index, name='index'),
 path('<int:posts_id>/create_comment', views.create_comment, name='create_comment'),
 path('', views.like, name='like'),
 path('',  views.dislike, name='dislike'),
 path('<int:posts_id>/', views.detail, name='detail'),
 path('', views.PostsList.as_view()),
 path('posts/add', views.PostsList.as_view()),
 path('posts/<int:posts_id>/edit/', views.edit_post, name='edit_post'),
 path('posts/<int:posts_id>/delete/', views.delete_post, name='delete_post'),

]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

apps/posts/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    author_name = models.CharField('Имя', max_length=50)

    def update_rating(self, new_rating):
        self.rating = new_rating
        self.save()

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)


class Post(models.Model):
    article = 'a'
    news = 'n'

    POST_TYPE = [
        (article, "Статья"),
        (news, "Новость")
    ]
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None)
    post_type = models.CharField(max_length=1, choices=POST_TYPE, default=article)
    cats = models.ManyToManyField(Category, through='PostCategory')
    post_title = models.CharField('Название', max_length=100)
    post_text = models.TextField('Текст')
    pub_date = models.DateTimeField('Дата публикации')
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        size = 50 if len(self.post_text) > 50 else len(self.post_text)
        return self.post_text[:size] + '...'

    def __str__(self):
        return self.post_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author_name = models.CharField('Имя автора', max_length=50)
    comment_text = models.CharField('Текст коммента', max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.id = 1/0
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

apps/posts/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from .models import Post, Comment, Category  # Дополнительно импортируем категорию, чтобы пользователь мог её выбрать
from .filters import PostFilter
from django.core.paginator import Paginator


class PostsList(ListView):
    paginate_by = 1
    model = Post
    template_name = 'list.html'
    context_object_name = 'posts'
    queryset = Post.objects.order_by('-id')


class Posts(ListView):
    model = Post
    template_name = 'list.html'
    context_object_name = 'posts'
    ordering = ['-pub_date']


def post(request, *args, **kwargs):
    # берём значения для нового товара из POST-запроса, отправленного на сервер
    name = request.POST['name']
    category_id = request.POST['category']
    pos = Post(name=name, category_id=category_id)  # создаём новую публикацию и сохраняем
    pos.save()
    return super().get(request, *args, **kwargs)  # отправляем пользователя обратно на GET-запрос.


def index(request):
    latest_posts_list = Post.objects.order_by('-pub_date')[:5]
    return render(request, 'posts/list.html', {'latest_posts_list': latest_posts_list})


def get_context_data(self, **kwargs):
    # забираем отфильтрованные объекты переопределяя метод get_context_data у наследуемого класса
    context = super().get_context_data(**kwargs)
    context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())  # вписываем наш фильтр в контекст
    return context


def detail(request, posts_id):
    try:
        p = Post.objects.get(id=posts_id)
    except:
        raise Http404("Статья не найдена")

    latest_comments_list = p.comment_set.order_by('-id')[:10]

    return render(request, 'posts/detail.html', {'posts': p, 'latest_comments_list': latest_comments_list})


def create_comment(request, posts_id):
    try:
        p = Post.objects.get(id=posts_id)
    except:
        raise Http404("Статья не найдена")

    p.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect(reverse('posts:detail', args=p.id,))


def like(comment_id=4):
    c = Comment.objects.get(id=comment_id)
    print(c)
    # return HttpResponseRedirect(reverse('posts:detail', args=c.id))


def dislike(posts_id):
    pass
    # try:
    #     p = Post.objects.get(id=posts_id)
    # except:
    #     raise Http404("Комментарий не найден")
    #
    # p.comment.post()
    # return HttpResponseRedirect(reverse('posts:detail', args=p.id))


def delete_post():
    print("Вы уверены, что хотите удалить публикацию?")
    answer = input('yes')
    if answer:
        Post.delete()
    else:
        pass


def edit_post():
    pass

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}Мой сайт{% endblock %}</title>
</head>
<body>
{% block content %}{%endblock%}

</body>
</html>

templates/default.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}Мой сайт{% endblock %}</title>
</head>
<body>
{% block content %}Это начальная страница{%endblock %}
<nav>
    <ul>
        {% for p in page_obj.paginator.page_range %}
        <li>
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endfor %}
    </ul>
</nav>
</body>
</html>

templates/posts/detail.html
{% extends 'default.html' %}

{% block title %} {{posts.posts_title}} {% endblock %}

{% block content %}

<h2>{{posts.post_title}}</h2>

<em>{{posts.pub_date}}</em>

<p>{{posts.post_text}}</p>



{% if posts.was_published_recently %}
НОВАЯ СТАТЬЯ
{% endif %}


<hr>

{% if latest_comments_list %}
    {% for c in latest_comments_list %}

<comment>
    <strong>{{c.author_name}}</strong>
    {{ c.comment_text }} {{c.rating}} {{c.id}}
    <form  action="{% url 'posts:like'%}" method="post">
      <button type="submit">👍</button>

    {% csrf_token %}
    </form>
            <form action="{% url 'posts:dislike'%}" method="post">
        {% csrf_token %}

        <button type="submit">👎</button>
        </form>

</comment>


    {% endfor %}
{% else %}
Коментарии не найдены! Станьте первым ;)
{% endif %}

<hr>

<form action="{% url 'posts:create_comment' posts.id %}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea><br>
    <button type="submit">Оставить комментарий</button>
</form>


{%endblock%}

templates/posts/list.html
{% extends 'default.html' %}
{% block title %}Последние статьи {% endblock %}
{% block content %}

    {% if latest_posts_list %}
<h1>
    Всего публикаций: {{ latest_posts_list | length }}
</h1>

      {% for p in latest_posts_list %}

<h3>
    {% if p.was_published_recently %}
    <font color="red">НОВАЯ СТАТЬЯ</font>
    {% endif %}<br>
            <a href="{% url 'posts:detail' p.id %}"> {{ p.post_title }}</a> {{p.pub_date}}<br>
</h3>

{{ p.post_text | truncatewords:20 }}<br>

Рейтинг: {{p.rating}}<br><br>

    {% endfor %}

    {% else %}
        Статьи не найдены =(
    {% endif %}

{% endblock content %}